# Generated by Django 2.2.7 on 2020-01-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='session_key',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
