# Generated by Django 2.2.7 on 2020-01-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200104_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextension1',
            name='school',
            field=models.CharField(blank=True, default='中南林业科技大学涉外学院', max_length=100),
        ),
    ]
