# Generated by Django 2.2.7 on 2020-01-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200104_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextension1',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=11, null=True, unique=True),
        ),
    ]
