# Generated by Django 2.2.7 on 2020-01-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200104_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_of_death',
            field=models.DateField(blank=True, help_text='时间格式：2019/10/04', null=True, verbose_name='died'),
        ),
    ]
