# Generated by Django 2.2.7 on 2020-01-04 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_oldsession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OldSession',
        ),
    ]
