# Generated by Django 2.2.7 on 2020-01-04 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_delete_oldsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldIp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OldSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, null=True)),
            ],
        ),
    ]
