# Generated by Django 2.2.7 on 2020-01-05 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_oldip_oldsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldip',
            name='ip',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='oldsession',
            name='session_key',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
