# Generated by Django 2.2.7 on 2020-01-05 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20200105_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldsession',
            name='session_key',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
