# Generated by Django 2.2.7 on 2020-01-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20200105_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextension1',
            name='school',
            field=models.CharField(blank=True, default='中南林业科技大学涉外学院', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userextension1',
            name='telephone',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
